{
 "title": "valera",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "market",
    "query": " SHOW TAG VALUES WITH KEY = \"market\""
   },
   {
    "name": "bot",
    "query": " SHOW TAG VALUES WITH KEY = \"bot\""
   }
  ]
 },
 "panels": [
  {
   "title": "Upstream prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "upstream" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "askPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "askPrice" ], "type": "alias" }
      ],
      [
       { "params": [ "bidPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bidPrice" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "market", "operator": "=~", "value": "/^$market$/" }
     ]
    }
   ]
  },
  {
   "title": "bookTicker",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "upstream" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "upstream",
     "query": "SELECT mean(\"askPrice\") AS \"askPrice\", mean(\"bidPrice\") AS \"bidPrice\" FROM \"upstream\" WHERE (\"market\" =~ /^$market$/) AND $timeFilter GROUP BY time($__interval), \"upstream\" fill(none)",
     "select": [
      [
       { "params": [ "askPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "askPrice" ], "type": "alias" }
      ],
      [
       { "params": [ "bidPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bidPrice" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "market", "operator": "=~", "value": "/^$market$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bot" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processor",
     "select": [
      [
       { "params": [ "ask_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bot_ask_price" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bot_bid_price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "market", "operator": "=~", "value": "/^$market$/" },
      { "condition": "AND", "key": "bot", "operator": "=~", "value": "/^$bot$/" }
     ]
    }
   ]
  },
  {
   "title": "Bot prices",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bot" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processor",
     "select": [
      [
       { "params": [ "ask_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bot_ask_price" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bot_bid_price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "bot", "operator": "=~", "value": "/^$bot$/" },
      { "condition": "AND", "key": "market", "operator": "=~", "value": "/^$market$/" }
     ]
    }
   ]
  }
 ]
}