accounts:
  bargainer_bot:
    upstream: peatio
    credentials: bargainer_bot
  deep_stoner_bot:
    upstream: peatio
    credentials: deep_stoner_bot
  market_bot:
    upstream: peatio
    credentials: market_bot
  binance:
    upstream: binance
    credentials: binance
  monolithos:
    upstream: monolithos
  equal:
    upstream: equal
  huobi:
    upstream: huobi
