drainers:
  huobi_websocket:
    class: HuobiWebsocketDrainer
    account: huobi
    markets:
      - HT-HRC20_USDT-HRC20
      - HT-HRC20_USDC-HRC20

  equal:
    class: EqualDrainer
    upstream: equal
    markets:
      - USDT-ERC20_USDT-BEP20
      - USDT-ERC20_USDC-ERC20
      - USDT-HRC20_USDT-BEP20
      - USDT-HRC20_USDT-ERC20
      - USDC-ERC20_USDC-BEP20
      - USDC-HRC20_USDC-ERC20
      - USDC-HRC20_USDC-BEP20

  monolithos:
    class: MonolithosDrainer
    account: monolithos

  binance_websocket:
    class: BinanceWebsocketDrainer
    account: binance

  peatio_websocket:
    class: PeatioWebsocketDrainer
    # for client only
    # TODO use client instead of account
    account: deep_stoner_bot

  peatio_rest:
    class: PeatioRestDrainer
    exclude_member_id: 6 # bargainer
    # TODO use client instead of account
    account: deep_stoner_bot

  # AccountDariner
  # собирает данные по аккаунтам
  #
  peatio_balance_deep_stoner:
    class: AccountDrainer
    account: deep_stoner_bot
    interval: 1

  peatio_balance_bargainer:
    class: AccountDrainer
    account: bargainer_bot
    interval: 1

  peatio_balance_market_bot:
    class: AccountDrainer
    account: market_bot
    interval: 1

  binance_account:
    class: AccountDrainer
    account: binance
    interval: 30

  # BinanceWebsocketDrainer
  #
  # он одинтакой )
  binance_userdata_websocket:
    class: BinanceUserdataWebsocketDrainer
    account: binance
