markets: 
  - base: BTC
    quote: USDT-ERC20
    binance_symbol: BTCUSDT
  - base: ETH
    quote: BTC
    binance_symbol: ETHBTC
  - base: BTC
    quote: MCR-ERC20
    binance_symbol: BTCRUB
    binance_quote: RUB
  - base: ETH
    quote: USDC-ERC20
    binance_symbol: ETHUSDC
  - base: ETH
    quote: USDT-ERC20
    binance_symbol: ETHUSDT
  - base: ETH
    quote: MCR-ERC20
    binance_symbol: ETHRUB
    binance_quote: RUB
  - base: USDT-ERC20
    quote: MCR-ERC20
    binance_symbol: USDTRUB
    binance_quote: RUB
  - base: BNB-BEP20
    quote: USDC-BEP20
    binance_symbol: BNBUSDC
  - base: BNB-BEP20
    quote: USDT-BEP20
    binance_symbol: BNBUSDT
  - base: MDT-ERC20
    quote: MCR-ERC20
    monolithos_symbol: MDT_MCR
  - base: MDT-ERC20
    quote: USDT-ERC20
    monolithos_symbol: MDT_USD
  - USDT-ERC20_USDT-BEP20
  - USDT-ERC20_USDC-ERC20
  - USDC-ERC20_USDC-BEP20
  - USDT-HRC20_USDT-BEP20
  - USDT-HRC20_USDT-ERC20
  - USDC-HRC20_USDC-ERC20
  - USDC-HRC20_USDC-BEP20
  - base: HT-HRC20
    quote: USDC-HRC20
    huobi_symbol: htusdt
  - base: HT-HRC20
    quote: USDT-HRC20
    huobi_symbol: htusdt
