default: &default
  async: true
  time_precision: ms
development:
  <<: *default
  database: valera_development

test:
  <<: *default
  database: valera_test

staging:
  <<: *default
  database: <%= ENV.fetch('INFLUXDB_DATABASE_NAME', "valera_staging") %>
production:
  <<: *default
  udp:
    host: <%= ENV.fetch("INFLUXDB_HOST", "127.0.0.1") %>
    port: <%= ENV.fetch("INFLUXDB_UDP_PORT", 8089) %>
  database: <%= ENV.fetch('INFLUXDB_DATABASE_NAME', "valera_production") %>
