defaults: &defaults
  polling_sleep: 0.1
  maker_sleep: 0.1

  influx:
    collectors: 'upstream'
    orders_updater: 'processor'

development:
  <<: *defaults
  polling_sleep: 1
  maker_sleep: 1
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
