defaults: &defaults
  markets: 
    - base: BTC
      quote: USDT-ERC20
      binance_symbol: BTCUSDT
    - base: ETH
      quote: BTC
      binance_symbol: ETHBTC
    - base: BTC
      quote: MCR-ERC20
      binance_symbol: BTCRUB
      binance_quote: RUB
    - base: ETH
      quote: USDC-ERC20
      binance_symbol: ETHUSDC
    - base: ETH
      quote: USDT-ERC20
      binance_symbol: ETHUSDT
    - base: ETH
      quote: MCR-ERC20
      binance_symbol: ETHRUB
      binance_quote: RUB
    - base: USDT-ERC20
      quote: MCR-ERC20
      binance_symbol: USDTRUB
      binance_quote: RUB
    - base: BNB-BEP20
      quote: USDC-BEP20
      binance_symbol: BNBUSDC
    - base: BNB-BEP20
      quote: USDT-BEP20
      binance_symbol: BNBUSDT
    - base: MDT-ERC20
      quote: MCR-ERC20
      monolithos_symbol: MDT_MCR
    - base: MDT-ERC20
      quote: USDT-ERC20
      monolithos_symbol: MDT_USD
    - USDT-ERC20_USDT-BEP20
    - USDT-ERC20_USDC-ERC20
    - USDC-ERC20_USDC-BEP20
    - USDT-HRC20_USDT-BEP20
    - USDT-HRC20_USDT-ERC20
    - USDC-HRC20_USDC-ERC20
    - USDC-HRC20_USDC-BEP20
    - base: HT-HRC20
      quote: USDC-HRC20
      huobi_symbol: htusdt
    - base: HT-HRC20
      quote: USDT-HRC20
      huobi_symbol: htusdt

  polling_sleep: 0.1
  maker_sleep: 0.1

  influx:
    collectors: 'upstream'
    orders_updater: 'processor'

  upstreams: 
    binance: 
      client: Valera::BinanceClient
      markets:
        - BTC_USDT-ERC20
        - BTC_MCR-ERC20
        - BNB-BEP20_USDC-BEP20
        - BNB-BEP20_USDT-BEP20
        - ETH_BTC
        - ETH_MCR-ERC20
        - ETH_USDC-ERC20
        - ETH_USDT-ERC20
        - USDT-ERC20_MCR-ERC20
    peatio:
      client: Valera::PeatioClient
    huobi:
      markets:
        - HT-HRC20_USDT-HRC20
        - HT-HRC20_USDC-HRC20
    monolithos:
      client: Valera::MonolithosClient
      markets:
        - MDT-ERC20_MCR-ERC20
        - MDT-ERC20_USDT-ERC20
    equal:
      markets:
        - USDT-ERC20_USDT-BEP20
        - USDT-ERC20_USDC-ERC20
        - USDC-ERC20_USDC-BEP20
        - USDT-HRC20_USDT-BEP20
        - USDT-HRC20_USDT-ERC20
        - USDC-HRC20_USDC-ERC20
        - USDC-HRC20_USDC-BEP20

  accounts:
    bargainer_bot:
      upstream: peatio
      credentials: bargainer_bot
    deep_stoner_bot:
      upstream: peatio
      credentials: deep_stoner_bot
    binance:
      upstream: binance
      credentials: binance
    monolithos:
      upstream: monolithos
    equal:
      upstream: equal
    huobi:
      upstream: huobi

  drainers:
    huobi_websocket:
      class: HuobiWebsocketDrainer
      account: huobi
      markets:
        - HT-HRC20_USDT-HRC20
        - HT-HRC20_USDC-HRC20

    equal:
      class: EqualDrainer
      upstream: equal
      markets:
        - USDT-ERC20_USDT-BEP20
        - USDT-ERC20_USDC-ERC20
        - USDT-HRC20_USDT-BEP20
        - USDT-HRC20_USDT-ERC20
        - USDC-ERC20_USDC-BEP20
        - USDC-HRC20_USDC-ERC20
        - USDC-HRC20_USDC-BEP20

    monolithos:
      class: MonolithosDrainer
      account: monolithos

    binance_websocket:
      class: BinanceWebsocketDrainer
      account: binance

    peatio_websocket:
      class: PeatioWebsocketDrainer
      account: deep_stoner_bot

    peatio_rest:
      class: PeatioRestDrainer
      account: deep_stoner_bot

    peatio_balance_deep_stoner:
      class: AccountDrainer
      account: deep_stoner_bot
      interval: 1

    peatio_balance_bargainer:
      class: AccountDrainer
      account: bargainer_bot
      interval: 1

    binance_account:
      class: AccountDrainer
      account: binance
      interval: 30

    binance_userdata_websocket:
      class: BinanceUserdataWebsocketDrainer
      account: binance

  strategies:
    equal_bargainer:
      class: BargainerStrategy
      account: bargainer_bot
      source_account: equal
      markets:
        - USDT-ERC20_USDT-BEP20
        - USDT-ERC20_USDC-ERC20
        - USDT-HRC20_USDT-BEP20
        - USDT-HRC20_USDT-ERC20
        - USDC-ERC20_USDC-BEP20
        - USDC-HRC20_USDC-ERC20
        - USDC-HRC20_USDC-BEP20

    huobi_bargainer:
      class: BargainerStrategy
      account: bargainer_bot
      source_account: huobi
      markets: 
        - HT-HRC20_USDT-HRC20
        - HT-HRC20_USDC-HRC20

    monolithos_bargainer:
      class: BargainerStrategy
      account: bargainer_bot
      source_account: monolithos
      markets: 
        - MDT-ERC20_MCR-ERC20
        - MDT-ERC20_USDT-ERC20

    binance_deep_stoner:
      class: DeepStonerStrategy
      account: deep_stoner_bot
      buyout_account: binance
      source_account: binance
      markets:
        - BTC_USDT-ERC20
        - ETH_BTC
        - BTC_MCR-ERC20
        - ETH_USDC-ERC20
        - ETH_USDT-ERC20
        - ETH_MCR-ERC20
        - USDT-ERC20_MCR-ERC20
        - BNB-BEP20_USDC-BEP20
        - BNB-BEP20_USDT-BEP20

    binance_bargainer:
      class: BargainerStrategy
      account: bargainer_bot
      source_account: binance
      markets: 
        - BTC_USDT-ERC20
        - ETH_BTC
        - BTC_MCR-ERC20
        - ETH_USDC-ERC20
        - ETH_USDT-ERC20
        - ETH_MCR-ERC20
        - USDT-ERC20_MCR-ERC20
        - BNB-BEP20_USDC-BEP20
        - BNB-BEP20_USDT-BEP20

development:
  <<: *defaults
  polling_sleep: 1
  maker_sleep: 1

  fake_accounts:
    bargainer_bot:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: test
    deep_stoner_bot:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: test
    binance:
      upstream: binance
      credentials: 
        name: binance
        api_key: test
        secret_key: test
    monolithos:
      upstream: monolithos

staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
  markets: 
    - base: BTC
      quote: USDT-ERC20
      binance_symbol: BTCUSDT
  drainers:
    binance_websocket:
      class: BinanceWebsocketDrainer
      account: binance

    peatio_websocket:
      class: PeatioWebsocketDrainer
      account: peatio1

    peatio_rest:
      class: PeatioRestDrainer
      account: peatio1

    peatio_balance_deep_stoner:
      class: AccountDrainer
      account: peatio1

    peatio_balance_bargainer:
      class: AccountDrainer
      account: binance

  upstreams: 
    binance:
      client: Valera::BinanceClient
    peatio:
      client: Valera::PeatioClient
    huobi:
      client: Valera::HuobiClient

  accounts:
    peatio1:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: text
    peatio2:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: text
    binance:
      upstream: binance
      credentials: 
        name: :binance
        api_key: test
        secret_key: test

  strategies:
    deep_stoner:
      class: DeepStonerStrategy
      comment: Арбитражник - глубокий наполнятель стакана
      account: peatio1
      buyout_account: binance
      markets: []

    bargainer:
      class: BargainerStrategy
      comment: Проторговщик, торгует на малые объёмы, иногда так получается что сделки закрываются на самого себя
      account: peatio2
      markets: []
